---
- name: Delete user from all systems (with scheduled time check)
  hosts: localhost
  gather_facts: false

  vars:
    username: "{{ username }}"
    delete_time: "{{ delete_time }}"  # Format: 2025-05-20T03:00:00

  tasks:
    - name: Debug input
      debug:
        msg: "Processing deletion for {{ username }} scheduled at {{ delete_time }}"

    - name: Convert delete_time to timestamp
      set_fact:
        scheduled_epoch: "{{ (delete_time | to_datetime('%Y-%m-%dT%H:%M:%S')).timestamp() | int }}"
        current_epoch: "{{ lookup('pipe', 'date +%s') | int }}"

    - name: Fail if scheduled time not reached
      when: current_epoch < scheduled_epoch
      fail:
        msg: "â° Not yet time to delete {{ username }} ({{ current_epoch }} < {{ scheduled_epoch }})"

    - name: Delete from Active Directory
      include_tasks: "../ad/delete/delete_user.yml"

    - name: Delete from Gmail
      include_tasks: "../gmail/delete/delete_user.yml"

   # - name: Delete from Linux
    #  include_tasks: "../linux/delete/delete_user.yml"

   # - name: Delete from GCP
    #  include_tasks: "../gcp/delete/delete_user.yml"
