# delete_users_batch.yml
---
- name: Batch delete users
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Loop users
      include_tasks: delete_user_single.yml
      loop: "{{ user_list }}"
      loop_control:
        loop_var: target
